### ISSUE TITLE
clarify / document episode release schedule (if possible)

### ISSUE THREAD

**Issue by knksmith57** [thechangelog/jsparty#3]
Heya Team,

Live streaming starts every Friday at 1500 eastern-- thanks for making that clear and obvious in the readme.

It might be useful to add another note regarding availability of the _recorded_ episode for people that miss the live showing.

Is there an average / expected timeline for that? Quick googling / changelog.com browsing is coming up empty.

Thanks!

**Comment by adamstac** [comment]
Thanks for the feedback @knksmith57!

We operate on a week to week schedule ~> record Friday and publish the following Friday. We'd like to shrink that time to record on Friday publish the following Tuesday but that hasn't happened yet.
